

;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2018 Hex-Rays, <support@hex-rays.com>           |
; |                      License info: 48-3015-72F4-DD                      |
; |                       Octavian Dima, personal use                       |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : FAB5D5349DF4D2EF7F15C9653F5E5873428638782DF1A77704A7606E9A196A65
; Input MD5    : 24F9E749F7755F9E18983A5F2715738E
; Input CRC32  : 7E469662

; File Name   : C:\Users\theis\Desktop\Projects\Sonic CD 0.02 Disassembly\IPX___.MMD
; Format      : Binary file
; Base Address: 0000h Range: 0000h - 033Ch Loaded length: 033Ch

; Processor       : 68000
; Target assembler: 680x0 Assembler in MRI compatible mode
; This file should be compiled with "as -M"

; ===========================================================================

; Segment type: Pure code
; segment "ROM"
                dc.b   0
                dc.b   0
                dc.l $FF0000
                dc.w $3FF
                dc.l $FF0000
                dc.l 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
                dc.l 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
                dc.l 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
                dc.l 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
; ---------------------------------------------------------------------------
                move.l  #$FF0212,($FFFD08).w
                bset    #1,($A12003).l
                moveq   #5,d0
                bsr.w   sub_286

loc_116:                                ; CODE XREF: ROM:0000015E↓j
                                        ; ROM:000001AA↓j ...
                moveq   #$B,d0
                bsr.w   sub_286
                tst.b   d1
                beq.w   loc_1A4
                tst.w   d0
                beq.w   loc_1AE
                bra.w   loc_254
; ---------------------------------------------------------------------------
                moveq   #6,d0
                bsr.w   sub_286
                mulu.w  #6,d0
                move.w  word_164(pc,d0.w),($FF1210).l
                move.b  byte_166(pc,d0.w),($FF123D).l
                move.b  byte_167(pc,d0.w),($FF127A).l
                move.w  byte_162(pc,d0.w),d0
                move.b  #0,($FF0580).l
                bsr.w   sub_286
                bra.w   loc_116
; ---------------------------------------------------------------------------
byte_162:       dc.b 0, 1
word_164:       dc.w 0
byte_166:       dc.b 1
byte_167:       dc.b 0, 0, 2, 0, 0, 0, 0, 0, 3, 0, 0, 2, 1, 0, 4, 0, 0
                dc.b 2, 0, 0, 7, 0, 1, 1, 0, 0, 8, 0, 1, 0, 0, 0, 9, 0
                dc.b 1, 2, 1, 0, $A, 0, 1, 2, 0, 0, $C, 0, 0, 0, 0, 0
                dc.b $24, 0, 0, 0, 0, 0, $25, 0, 0, 0, 0
; ---------------------------------------------------------------------------

loc_1A4:                                ; CODE XREF: ROM:0000011E↑j
                moveq   #$24,d0 ; '$'
                bsr.w   sub_286
                bra.w   loc_116
; ---------------------------------------------------------------------------

loc_1AE:                                ; CODE XREF: ROM:00000124↑j
                move.b  #1,($FF123D).l
                move.b  #0,($FF0580).l
                bsr.w   sub_1D8
                tst.b   ($FF1212).l
                beq.s   loc_1CE
                bsr.w   sub_1E8

loc_1CE:                                ; CODE XREF: ROM:000001C8↑j
                moveq   #$25,d0 ; '%'
                bsr.w   sub_286
                bra.w   loc_116

; =============== S U B R O U T I N E =======================================


sub_1D8:                                ; CODE XREF: ROM:000001BE↑p
                lea     word_244(pc),a0
                move.w  #0,($FF1210).l
                bra.w   loc_1F8
; End of function sub_1D8


; =============== S U B R O U T I N E =======================================


sub_1E8:                                ; CODE XREF: ROM:000001CA↑p
                lea     word_24C(pc),a0
                move.w  #1,($FF1210).l
                bra.w   *+4
; ---------------------------------------------------------------------------

loc_1F8:                                ; CODE XREF: sub_1D8+C↑j
                                        ; sub_1E8+C↑j
                move.w  0(a0),d0

loc_1FC:                                ; CODE XREF: sub_1E8+3E↓j
                                        ; sub_1E8+46↓j ...
                bsr.w   sub_286
                tst.b   ($FF1212).l
                beq.s   locret_242
                btst    #7,($FF123D).l
                beq.s   locret_242
                moveq   #$C,d0
                bsr.w   sub_286
                move.b  ($FF123D).l,d1
                move.w  2(a0),d0
                andi.b  #$7F,d1
                beq.s   loc_1FC
                move.w  0(a0),d0
                subq.b  #1,d1
                beq.s   loc_1FC
                move.w  6(a0),d0
                tst.b   ($FF127A).l
                beq.s   loc_1FC
                move.w  4(a0),d0
                bra.s   loc_1FC
; ---------------------------------------------------------------------------

locret_242:                             ; CODE XREF: sub_1E8+1E↑j
                                        ; sub_1E8+28↑j
                rts
; End of function sub_1E8

; ---------------------------------------------------------------------------
word_244:       dc.w 1, 2, 3, 4         ; DATA XREF: sub_1D8↑o
word_24C:       dc.w 7, 8, 9, $A        ; DATA XREF: sub_1E8↑o
; ---------------------------------------------------------------------------

loc_254:                                ; CODE XREF: ROM:00000128↑j
                                        ; ROM:loc_280↓j
                moveq   #$D,d0
                bsr.w   sub_286
                move.w  d0,($FF0594).l
                beq.w   loc_116
                add.w   d0,d0
                move.w  loc_280(pc,d0.w),d0
                move.b  #1,($FF0580).l
                bsr.w   sub_286
                move.l  ($FF1222).l,($FF0590).l

loc_280:
                bra.s   loc_254
; ---------------------------------------------------------------------------
                dc.w 1, 7

; =============== S U B R O U T I N E =======================================


sub_286:                                ; CODE XREF: ROM:00000112↑p
                                        ; ROM:00000118↑p ...
                move.l  a0,-(sp)
                bsr.w   sub_31C
                move.l  ($200008).l,d0
                beq.s   loc_30E
                movea.l d0,a0
                move.l  ($200002).l,d0
                beq.s   loc_2B2
                movea.l d0,a2
                lea     ($200100).l,a1
                move.w  ($200006).l,d7

loc_2AC:                                ; CODE XREF: sub_286+28↓j
                move.l  (a1)+,(a2)+
                dbf     d7,loc_2AC

loc_2B2:                                ; CODE XREF: sub_286+16↑j
                move.l  ($20000E).l,d0
                beq.s   loc_2BE
                move.l  d0,($FFFD0E).w

loc_2BE:                                ; CODE XREF: sub_286+32↑j
                move.l  ($200010).l,d0
                beq.s   loc_2CA
                move.l  d0,($FFFD08).w

loc_2CA:                                ; CODE XREF: sub_286+3E↑j
                btst    #6,($200000).l
                beq.s   loc_2DC
                bset    #1,($A12003).l

loc_2DC:                                ; CODE XREF: sub_286+4C↑j
                jsr     (a0)
                move.b  #0,($FF0583).l
                move.l  #$FF021A,($FFFD0E).w
                move.l  #$FF0212,($FFFD08).w
                move.w  #$8134,($FF0596).l
                move.w  #$8134,($C00004).l
                bset    #1,($A12003).l

loc_30E:                                ; CODE XREF: sub_286+C↑j
                movea.l (sp)+,a0
                rts
; End of function sub_286

; ---------------------------------------------------------------------------
                bset    #0,($A12000).l
                rte

; =============== S U B R O U T I N E =======================================


sub_31C:                                ; CODE XREF: sub_286+2↑p
                move.w  d0,($A12010).l

loc_322:                                ; CODE XREF: sub_31C+C↓j
                tst.w   ($A12020).l
                beq.s   loc_322
                move.w  #0,($A12010).l

loc_332:                                ; CODE XREF: sub_31C+1C↓j
                tst.w   ($A12020).l
                bne.s   loc_332
                rts
; End of function sub_31C

; end of 'ROM'


                END
